version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  bot_sender:
    build: ./bot_sender
    depends_on:
      - rabbitmq

  bot_receiver:
    build: ./bot_receiver
    depends_on:
      - rabbitmq
